In [3]:
import numpy as np
import cv2, PIL
from cv2 import aruco
import matplotlib.pyplot as plt
import matplotlib as mpl
import pandas as pd

Mostrarmos los identificadores de los marcadores detectados.

In [6]:
import os

def findArucoMarkers(img, markerSize = 6, totalMarkers=250, draw=True):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    key = getattr(aruco, f'DICT_{markerSize}X{markerSize}_{totalMarkers}')
    print(key)
    arucoDict = aruco.getPredefinedDictionary(key)
    arucoParam = aruco.DetectorParameters()
    detector = cv2.aruco.ArucoDetector(arucoDict, arucoParam)
    bboxs, ids, rejected = detector.detectMarkers(gray)
    print(ids)

cap = cv2.VideoCapture(0)
while True:
    success, img = cap.read()
    findArucoMarkers(img)
    cv2.imshow('img',img)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break
cap.release()
cv2.destroyAllWindows()

10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None
10
None


Dibujamos los marcos  de los marcadores detectados.

In [7]:
import cv2
import cv2.aruco as aruco
import numpy as np
import os
def findArucoMarkers(img, markerSize = 6, totalMarkers=250, draw=True):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    key = getattr(aruco, f'DICT_{markerSize}X{markerSize}_{totalMarkers}')
    arucoDict = aruco.getPredefinedDictionary(key)
    arucoParam = aruco.DetectorParameters()
    detector = cv2.aruco.ArucoDetector(arucoDict, arucoParam)
    bboxs, ids, rejected = detector.detectMarkers(gray)
    print(ids)
    if draw:
        aruco.drawDetectedMarkers(img, bboxs) 
cap = cv2.VideoCapture(0)
while True:
    success, img = cap.read()
    findArucoMarkers(img)
    cv2.imshow('img',img)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break
cap.release()
cv2.destroyAllWindows()

None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
[[12]]
[[1

Devolvemos los bordes y el id del marcador detectado.

In [8]:
import cv2
import cv2.aruco as aruco
import numpy as np
import os
def findArucoMarkers(img, markerSize = 6, totalMarkers=250, draw=True):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    key = getattr(aruco, f'DICT_{markerSize}X{markerSize}_{totalMarkers}')
    arucoDict = aruco.getPredefinedDictionary(key)
    arucoParam = aruco.DetectorParameters()
    detector = cv2.aruco.ArucoDetector(arucoDict, arucoParam)
    bboxs, ids, rejected = detector.detectMarkers(gray)
    # print(ids)
    if draw:
        aruco.drawDetectedMarkers(img, bboxs) 
    return [bboxs, ids]

cap = cv2.VideoCapture(0)   
while True:
    success, img = cap.read()
    arucofound = findArucoMarkers(img)
     # loop through all the markers and augment each one
    if  len(arucofound[0])!=0:
        for bbox, id in zip(arucofound[0], arucofound[1]):
            print(bbox)
    cv2.imshow('img',img)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break
cap.release()
cv2.destroyAllWindows()

[[[331. 421.]
  [353. 359.]
  [415. 392.]
  [397. 455.]]]
[[[233. 376.]
  [262. 314.]
  [325. 345.]
  [301. 409.]]]
[[[320. 418.]
  [343. 354.]
  [404. 386.]
  [387. 450.]]]
[[[313. 410.]
  [333. 347.]
  [396. 375.]
  [380. 440.]]]
[[[123. 298.]
  [154. 237.]
  [224. 264.]
  [196. 326.]]]
[[[214. 333.]
  [240. 271.]
  [308. 297.]
  [287. 361.]]]
[[[304. 368.]
  [324. 304.]
  [391. 330.]
  [375. 395.]]]
[[[123. 298.]
  [154. 237.]
  [224. 264.]
  [196. 326.]]]
[[[214. 333.]
  [240. 271.]
  [308. 297.]
  [287. 361.]]]
[[[304. 368.]
  [324. 304.]
  [391. 330.]
  [375. 395.]]]
[[[121. 296.]
  [154. 234.]
  [223. 261.]
  [197. 325.]]]
[[[215. 332.]
  [240. 268.]
  [309. 294.]
  [288. 359.]]]
[[[306. 366.]
  [325. 300.]
  [392. 326.]
  [377. 392.]]]
[[[118. 304.]
  [148. 237.]
  [221. 261.]
  [197. 329.]]]
[[[215. 335.]
  [239. 267.]
  [311. 291.]
  [292. 360.]]]
[[[310. 365.]
  [327. 296.]
  [397. 319.]
  [385. 389.]]]
[[[115. 311.]
  [143. 241.]
  [219. 263.]
  [195. 333.]]]
[[[214. 338.]


### Remplazamiento del objeto
Se definen las coordenadas de los ementos del marcador detectado
*  **tl** arriba a la izquierda,
*  **bl** abajo a la izquierda,
*  **br** abajo a la derecha,
*  **tr** arriba a la derecha

### Homografía
La homografía es una transformación que asigna los puntos de un punto al punto correspondiente en otra imagen. La homografía es una matriz de 3×3:

![](./fig/2024-06-26-19-02-32.png)

Si 2 puntos no están en el mismo plano entonces tenemos que usar 2 homógrafos. De manera similar, para *n* planos, tenemos que usar *n* homógrafos. Si tenemos más homógrafos, entonces debemos manejarlos todos correctamente. Por eso utilizamos la coincidencia de funciones.

**Coincidencia de características:** la coincidencia de características significa encontrar características correspondientes de dos conjuntos de datos similares en función de una distancia de búsqueda.

**Homografía:** Para detectar la homografía del objeto tenemos que obtener la matriz y usar la función ``findHomography()`` para obtener la homografía del objeto. 

 La computadora no puede encontrar su homógrafo si no tiene suficientes puntos de correspondencia. Por lo tanto, necesitamos encontrar suficientes puntos de correspondencia para encontrar la homografía del objeto. Cuando intentamos cambiar o mover el objeto en otra dirección, los humanos pueden ver objetos cercanos más grandes que objetos lejanos, aquí la perspectiva está cambiando. Esto se llama **transformación de perspectiva**.

In [9]:
import cv2
import cv2.aruco as aruco
import numpy as np
import os
def findArucoMarkers(img, markerSize = 6, totalMarkers=250, draw=True):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    key = getattr(aruco, f'DICT_{markerSize}X{markerSize}_{totalMarkers}')
    arucoDict = aruco.getPredefinedDictionary(key)
    arucoParam = aruco.DetectorParameters()
    detector = cv2.aruco.ArucoDetector(arucoDict, arucoParam)
    bboxs, ids, rejected = detector.detectMarkers(gray)
    # print(ids)
    if draw:
        aruco.drawDetectedMarkers(img, bboxs)
    return [bboxs, ids]

def arucoAug(bbox, id, img, imgAug, drawId = True):
    tl = bbox[0][0][0], bbox[0][0][1]
    tr = bbox[0][1][0], bbox[0][1][1]
    br = bbox[0][2][0], bbox[0][2][1]
    bl = bbox[0][3][0], bbox[0][3][1]
    h, w, c = imgAug.shape
    pts1 = np.array([tl, tr, br, bl])
    pts2 = np.float32([[0,0], [w,0], [w,h], [0,h]])
    matrix, _ = cv2.findHomography(pts2, pts1)
    imgout = cv2.warpPerspective(imgAug, matrix, (img.shape[1], img.shape[0]))
    return imgout
cap = cv2.VideoCapture(0)
imgAug = cv2.imread("mini.png")

while True:
    success, img = cap.read()
    arucofound = findArucoMarkers(img)
     # loop through all the markers and augment each one
    if  len(arucofound[0])!=0:
        for bbox, id in zip(arucofound[0], arucofound[1]):
            img = arucoAug(bbox, id, img, imgAug)
    cv2.imshow('img',img)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break
cap.release()
cv2.destroyAllWindows()

Un polígono convexo es un polígono en el que los segmentos de línea entre los puntos no van hacia adentro y los vértices del polígono apuntan hacia afuera. Los ángulos interiores miden menos de 180°. OpenCV proporciona el método ``cv2.fillConvexPoly()`` para dibujar un polígono convexo relleno en una imagen. 

In [10]:
import cv2
import cv2.aruco as aruco
import numpy as np
import os
def findArucoMarkers(img, markerSize = 6, totalMarkers=250, draw=True):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    key = getattr(aruco, f'DICT_{markerSize}X{markerSize}_{totalMarkers}')
    arucoDict = aruco.getPredefinedDictionary(key)
    arucoParam = aruco.DetectorParameters()
    detector = cv2.aruco.ArucoDetector(arucoDict, arucoParam)
    bboxs, ids, rejected = detector.detectMarkers(gray)
    # print(ids)
    if draw:
        aruco.drawDetectedMarkers(img, bboxs)
    return [bboxs, ids]

def arucoAug(bbox, id, img, imgAug, drawId = True):
    tl = bbox[0][0][0], bbox[0][0][1]
    tr = bbox[0][1][0], bbox[0][1][1]
    br = bbox[0][2][0], bbox[0][2][1]
    bl = bbox[0][3][0], bbox[0][3][1]
    h, w, c = imgAug.shape
    pts1 = np.array([tl, tr, br, bl])
    pts2 = np.float32([[0,0], [w,0], [w,h], [0,h]])
    matrix, _ = cv2.findHomography(pts2, pts1)
    imgout = cv2.warpPerspective(imgAug, matrix, (img.shape[1], img.shape[0]))
    cv2.fillConvexPoly(img, pts1.astype(int), (0, 0, 0))
    imgout = img + imgout
    return imgout
cap = cv2.VideoCapture(0)
imgAug = cv2.imread("mini.png")
while True:
    success, img = cap.read()
    arucofound = findArucoMarkers(img)
    # loop through all the markers and augment each one
    if len(arucofound[0])!=0:
        for bbox, id in zip(arucofound[0], arucofound[1]):
            img = arucoAug(bbox, id, img, imgAug)
    cv2.imshow('img',img)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break
cap.release()
cv2.destroyAllWindows()